# Generated by Django 5.1.3 on 2024-12-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='')),
                ('address', models.CharField(max_length=60)),
                ('phone_number', models.IntegerField()),
                ('bidding_limit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(max_length=60)),
                ('is_holiday', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Session_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Auction_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('join_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auction.bidder', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Member_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50, verbose_name='')),
                ('auction_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction_user', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50, verbose_name='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('payment_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50, verbose_name='pending , completed')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.bidder', verbose_name='Bidder')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('is_active', models.BooleanField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.bidder', verbose_name='')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.product', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Aucted_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_bid', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('auction_date', models.DateTimeField()),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.bidder', verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.product', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('winning_bid', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('auction_end_time', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.product', verbose_name='Product')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.bidder', verbose_name='Bidder')),
            ],
        ),
        migrations.CreateModel(
            name='Send_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.bidder', verbose_name='Bidder')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.category', verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.sub_category', verbose_name='Sub_Category'),
        ),
    ]
