# Generated by Django 5.1.3 on 2024-12-04 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Start-Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('end_date', models.DateTimeField(verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('submited_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('auctioner', 'Auctioner'), ('bidder', 'Bidder')], max_length=50, verbose_name='')),
                ('address', models.CharField(max_length=50, verbose_name='')),
                ('business_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('verified', models.BooleanField(default=False, verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.RemoveField(
            model_name='aucted_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='aucted_product',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='auction_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='member_fee',
            name='auction_user',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='send_feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='result',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='result',
            name='product',
        ),
        migrations.DeleteModel(
            name='Session_date',
        ),
        migrations.DeleteModel(
            name='Session_Time',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.user_profile', verbose_name=''),
        ),
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.user_profile', verbose_name='Owner'),
        ),
        migrations.DeleteModel(
            name='Aucted_Product',
        ),
        migrations.DeleteModel(
            name='Auction_User',
        ),
        migrations.DeleteModel(
            name='Member_fee',
        ),
        migrations.DeleteModel(
            name='Send_Feedback',
        ),
        migrations.DeleteModel(
            name='Bidder',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
